[_]
schema-version = "0.2"

[io.buildpacks]
# Exclude files from local Pack CLI builds, where .gitignore doesn't apply.
exclude = [
    "__pycache__",
    ".git",
    ".github",
    ".venv",
    ".DS_Store",
    ".env",
]
